### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-rykhl-siam#2]
```
./arfc-pres.tex:70: Undefined control sequence.
<argument> \@@magyar@captionfix

l.70 \begin{document}

./arfc-pres.tex:70:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on arfc-pres.log.
make: *** [all-via-pdf] Error 1
```

This is being caused by the captions package. I'm not sure if you use it, but it won't build on my machine if this is included. Will submit fixing pr.

**Comment by andrewryh** [comment]
I didn't use it.
That is weird because it is built fine for me.

**Comment by katyhuff** [comment]
tex builds can vary pretty dramatically across platforms -- who knows.
